### ISSUE TITLE
Release 2.1.3

### ISSUE THREAD

**Issue by legobeat** [ethereum/js-ethereum-cryptography#104]
Would be much appreciated with a release incorporating these changes merged since last release `2.1.2`:

- #96 
- #103 
- (unrelated: #94)

Given the pinning on specific versions of dependencies, defaulting users to the latest versions of noble packages without need of forcing resolutions etc seems good.

Related: #93

**Comment by paulmillr** [comment]
done

>  defaulting users to the latest versions of noble packages

If my npm key gets stolen, that could mean ETH wallets would get malwared. The risk for what? Removing the hassle of specifying resolutions sometimes? Doesn't seem like a good idea.

**Comment by paulmillr** [comment]
> getting releases out as dependencies are updated (like you are now doing!) is good

agree

**Comment by paulmillr** [comment]
published now, missed the publish since all my other repos do this via github CI, and in here there's no CI set up, will need to fix it
