### ISSUE TITLE
Bump @noble and @scure dependencies

### ISSUE THREAD

**Issue by legobeat** [ethereum/js-ethereum-cryptography#110]
`@noble/curves@1.4.0` contains a few desired fixes and updates.
AIUI, updating `@noble/curves` to `1.4.0` implies also upgrading the rest of the `@noble/` and `@scure/` suites to align versions.

#### Related
- [ ] #105 
- [ ] #106 
- [ ] #107 
- [ ] #108

**Comment by paulmillr** [comment]
@legobeat could you submit a pull request?

**Comment by legobeat** [comment]
> @legobeat could you submit a pull request?

@paulmillr Certainly! #111
