### ISSUE TITLE
Remove 0x prefix in hexToBytes

### ISSUE THREAD

**Issue by frangio** [ethereum/js-ethereum-cryptography#12]
When I saw `hexToBytes` I expected it to work on `0x`-prefixed strings, but found that it doesn't parse them as expected.

Current results:

```
> e.hexToBytes('0xab')
Uint8Array(2) [ 0, 171 ]
> e.hexToBytes('ab')
Uint8Array(1) [ 171 ]
```

What are your thoughts on removing the `0x` prefix automatically?

**Comment by paulmillr** [comment]
Sure.

**Comment by paulmillr** [comment]
#46
