### ISSUE TITLE
keccak fails on alpine linux

### ISSUE THREAD

**Issue by wanseob** [ethereum/js-ethereum-cryptography#3]
On alpine linux (node:12-alpine docker image),`ethereumjs-tx` fails to sign transaction because the `keccak` function fails on alpine linux. It seems only a specific case for alpine linux. works well on ubuntu.

https://github.com/cryptocoinjs/keccak/issues/15

**Comment by alcuadrado** [comment]
Closing this issue as it was followed and fixed in https://github.com/cryptocoinjs/keccak/issues/15
