### ISSUE TITLE
Do we have support for base64 encoding in util package?

### ISSUE THREAD

**Issue by christianxiao** [ethereum/js-ethereum-cryptography#38]
I checked the util package and don't find the base64 util, I guess this is a common feature that we can support.
For example, when we use AES to encode something to hex, then commonly we use base64 to encode the string and store in disk.
If you add this feature, I guess that will help a lot of people, thank you

**Comment by paulmillr** [comment]
You can use `@scure/base` directly, which is a dependency of js-e-c. I don't think exposing it makes sense — it's a rare feature in eth context really.

**Comment by alcuadrado** [comment]
I agree with @paulmillr, so I'm closing this issue.
