### ISSUE TITLE
node_modules/ethereum-cryptography/utils.d.ts(11,11): error TS2304: Cannot find name 'Crypto'.

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/js-ethereum-cryptography#66]
Hello,
I set `"lib": ["ES2021"]` at `compilerOptions` in my `tsconfg.json`  and this caused the error: 

> node_modules/ethereum-cryptography/utils.d.ts(11,11): error TS2304: Cannot find name 'Crypto'.

Could you please help with this? (I do not want to use skipLibCheck as I do not want to force the users of the library I am working on to use the same.)

Thanks,

**Comment by alcuadrado** [comment]
hey @Muhammad-Altabba,

Can you share more info about your setup? Thanks

**Comment by Muhammad-Altabba** [comment]
Thanks @alcuadrado,
It is the web3.js version 4.x (https://github.com/web3/web3.js/tree/4.x). And adding `"lib": ["ES2021"],` to the `compilerOptions` at `tsconfig.json` at the root folder, and then running `yarn` would produce the mentioned error.

**Comment by mpetrunic** [comment]
@alcuadrado To give more context, since web3.js should work in both nodejs and browser we have DOM types disabled in tsconfig which causes errors as this library expects DOM types to be available.

**Comment by mpetrunic** [comment]
https://github.com/ethereum/js-ethereum-cryptography/pull/75 Should fix it^^
