### ISSUE TITLE
Same methods are working diferent in client and server sides

### ISSUE THREAD

**Issue by acristoni** [ethereum/js-ethereum-cryptography#70]
I pretend to send a signature from the client and recover the public key from the server-side but is not working, just for a test I did the code above and I found, or at least I presume that, an issue...

if I implement this routine in my client app, works fine, but if I do the same thing on my server side it returns an error: 

Routine:
  const [signature, rec] = await secp.sign(hashMessage, privateKey, { recovered: true })
  const signatureHex = bytesToHex(signature)
  const recoveredKey = secp.recoverPublicKey(hashMessage, signatureHex, rec);

Error:
 throw new TypeError('hexToBytes: expected string, got ' + typeof hex);
              ^
TypeError: hexToBytes: expected string, got object

**Comment by paulmillr** [comment]
You need to post a full stack trace and values of hashMessage, privateKey (you can replace those with some other value that also throws error)

**Comment by acristoni** [comment]
**First values passed:**

> privateKey: 33b24608ef3bfd75f7926345820a177859147e3321df23488021460c7822e0c1,

> hashMessage: Uint8Array(32) [106, 57, 81, 126, 172, 144, 69, 139, 46, 29, 83, 121, 90, 180, 110, 172, 128, 148, 115, 248, 77, 35, 115, 3, 101, 97, 199, 5, 149, 97, 248, 61, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']

I did some tests on back-end, only works when I convert hashMessage to Hex too, just like I had already done with the private key.

What confused me was the README being like this:
>function recoverPublicKey(msgHash: Uint8Array, signature: Uint8Array, recovery: number): Uint8Array | undefined;

**Thank you very much for your help and for this package, it helped a lot!**

**Comment by alcuadrado** [comment]
Can you post the calls you are doing in node and the browser? Thanks

**Comment by acristoni** [comment]
**from React:**
```bash
  async function transfer(evt) {
    evt.preventDefault();

    const payload = JSON.stringify({
      sender: address,
      amount: parseInt(sendAmount),
      recipient
    })
    const hashMessage = bytesToHex(sha256(utf8ToBytes(payload)))

    const [signature, rec] = await secp.sign(hashMessage, privateKey, { recovered: true })
    const signatureHex = bytesToHex(signature)

    try {
      const {
        data: { balance },
      } = await server.post(`send`, {
        recipient,
        amount: parseInt(sendAmount),
        hashMessage,
        signature: signatureHex,
        rec
      });
      setBalance(balance);
    } catch (ex) {
      alert(ex.response.data.message);
    }
  }
```
**Server, Express.js:**
```bash
app.post("/send", (req, res) => {
  const { recipient, amount, hashMessage, signature, rec } = req.body;  
  const sender = bytesToHex(secp.recoverPublicKey(hashMessage, signature, rec));

  setInitialBalance(sender);
  setInitialBalance(recipient);

  if (balances[sender] < amount) {
    res.status(400).send({ message: "Not enough funds!" });
  } else {
    balances[sender] -= amount;
    balances[recipient] += amount;
    res.send({ balance: balances[sender] });
  }
});
```

**Comment by paulmillr** [comment]
```ts
import * as secp from '@noble/secp256k1';
const bytesToHex = secp.utils.bytesToHex;
const priv = '33b24608ef3bfd75f7926345820a177859147e3321df23488021460c7822e0c1';
const hashMessage = new Uint8Array([106, 57, 81, 126, 172, 144, 69, 139, 46, 29, 83, 121, 90, 180, 110, 172, 128, 148, 115, 248, 77, 35, 115, 3, 101, 97, 199, 5, 149, 97, 248, 61]);
(async () => {
  const pub = secp.getPublicKey(priv, false);
  console.log('public key', bytesToHex(pub));
  const [signature, rec] = await secp.sign(hashMessage, priv, {recovered: true});
  console.log('signature', bytesToHex(signature))
  const sender = secp.recoverPublicKey(hashMessage, signature, rec);
  console.log('recovered', bytesToHex(sender));
  console.log('equals', bytesToHex(pub) === bytesToHex(sender));
})();
```

@acristoni Works properly for me. The values match.

**Comment by acristoni** [comment]
@paulmillr What you did works appropriately for me too.

I was wrong, the error was because when I was sending from client to server the hashMessage, as Uint8Array, I was receiving a plain object on server, and converting this object received to a Uint8Array, everything works fine.

So all fine, with this:
>function recoverPublicKey(msgHash: Uint8Array, signature: Uint8Array, recovery: number): Uint8Array | undefined;

**Thanks!**
