### ISSUE TITLE
Build fails when project depends on this package

### ISSUE THREAD

**Issue by diliburong** [ethereum/js-ethereum-cryptography#86]
When using version 2.1.0. build failed

`Module not found: Error: Package path ./keccak is not exported from package /opt/atlassian/pipelines/agent/build/node_modules/@toruslabs/base-controllers/node_modules/ethereum-cryptography (see exports field in /opt/atlassian/pipelines/agent/build/node_modules/@toruslabs/base-controllers/node_modules/ethereum-cryptography/package.json)`

**Comment by diliburong** [comment]
may be caused by change https://github.com/ethereum/js-ethereum-cryptography/commit/06b37c538e8481940f0e714456bbdf514661e9b8

**Comment by samaritanz** [comment]
same issue

**Comment by XenriseZPH** [comment]
same issue

**Comment by XenriseZPH** [comment]
I have the same issue, web3auth depends on this package

**Comment by IDChats** [comment]
the same issue

**Comment by codingbiro** [comment]
As @diliburong pointed out, there might have been a change in the latest release which caused this issue.

As a temporary fix, you can override the nested dependency to an older version (v2.0.0 fixed it in my case):
```
"dependencies": {
    "web3": "4.0.2"
},
"resolutions": {
    "ethereum-cryptography": "2.0.0"
}
  ```
These two are defined in your `package.json` when using Yarn. If you use NPM, take a look at: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by NotCentralised** [comment]
> As @diliburong pointed out, there might have been a change in the latest release which caused this issue.
> 
> As a temporary fix, you can override the nested dependency to an older version (v2.0.0 fixed it in my case):
> 
> ```
> "dependencies": {
>     "web3": "4.0.2"
> },
> "resolutions": {
>     "ethereum-cryptography": "2.0.0"
> }
> ```
> 
> I am using `web3` which depends on this package, and I defined `resolutions` in `package.json` to override the dependency with Yarn. If you use NPM, take a look at: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

this worked for me....

**Comment by NotCentralised** [comment]
> As @diliburong pointed out, there might have been a change in the latest release which caused this issue.
> 
> As a temporary fix, you can override the nested dependency to an older version (v2.0.0 fixed it in my case):
> 
> ```
> "dependencies": {
>     "web3": "4.0.2"
> },
> "resolutions": {
>     "ethereum-cryptography": "2.0.0"
> }
> ```
> 
> I am using `web3` which depends on this package, and I defined `resolutions` in `package.json` to override the dependency with Yarn. If you use NPM, take a look at: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

although this builds, there are secondary effects which cause issues...
